export const slideInstructions: any = {
  story: [
    { lvl: 1, start: 1, end: 8 },
    { lvl: 5, start: 9, end: 11 },
    { lvl: 18, start: 12, end: 16 },
    { lvl: 37, start: 17, end: 19 },
    { lvl: 51, start: 20, end: 25 }
  ],
  //,{lvl:25,start:26,end:31}
  ending: [26, 31],
  notrans: [3],
  gifs: [5, 12, 13, 22, 26],
  sfx: {
    3: "poof",
    26: "alarm",
    20: "tick"
  }
};

//export const pulse:

//export const screenshots:

export const vulgarities: any = [
  "cunt",
  "fuck",
  "sex",
  "shit",
  "bitch",
  "nigger",
  "kike",
  "asshole",
  "arse",
  "christ",
  "cock",
  "bastard",
  "nigga",
  "twat",
  "shitass",
  "crap",
  "suck",
  "blowjob"
];

export const errors: any = [
  "nope",
  "nuh-uh",
  "sorry",
  "no can do",
  "error",
  "no way",
  "not allowed",
  "wrong",
  "too bad",
  "tough luck",
  "shame",
  "try again",
  "no no no",
  "tsk tsk",
  "nuh-uh",
  "nice try",
  "no means no",
  ":(",
  "404",
  "NaN",
  "wah",
  "(;_;)",
  "=/",
  "<:("
];
//,
export const mockings: any = [
  "hello?",
  "You there?",
  "?",
  "wasting time?",
  "??",
  "time's up",
  "come on!",
  "move it!",
  "yoo hoo",
  "tick tock"
];

export const impatient: any = ["soon", "patience", "not yet"];

export const disallowed: any = ["not this time", "not now", "not working now"];

export const onfire: any = [
  "ouch",
  "very hot",
  "it burns",
  "scalding",
  "such heat"
];

export const newchart: any = {
  type: "line",
  data: {
    datasets: [
      {
        label: "Alpha",
        lineTension: 0,
        borderColor: "rgba(255,50,50,.8)",
        pointBorderWidth: 3,
        pointStyle: "triangle",

        data: []
      },
      {
        label: "Beta",
        lineTension: 0,
        borderColor: "rgba(60,200,60,.8)",
        pointBorderWidth: 3,
        pointStyle: "rectRot",

        data: []
      },
      {
        label: "Gamma",
        lineTension: 0,
        borderColor: "rgba(60,60,150,.8)",
        pointBorderWidth: 3,
        pointStyle: "star",

        data: []
      }
    ]
  },
  options: {
    bezierCurve: true,
    lineTension: 0,
    responsive: true,
    maintainAspectRatio: true,
    aspectRatio:1.79,
    animation: false,
    scales: {
      yAxes: [
        {
          type: "linear",
          gridLines: {
            display: true,
            color: "rgba(255, 0, 0, .2)",
            borderDash: [8, 4]
          },
          ticks: {
            fontSize: 16
          }
        }
      ],
      xAxes: [
        {
          type: "linear",
          position: "bottom",
          gridLines: {
            display: true,
            color: "rgba(255, 0, 0, .2)",
            borderDash: [8, 4]
          },
          ticks: {
            fontSize: 16
          }
        }
      ]
    },
    legend: {
      display: false
    },
    tooltips: {
      enabled: false
    },
    //---------------------------------------
    // Container for pan options
    pan: {
      // Boolean to enable panning
      enabled: true,

      // Panning directions. Remove the appropriate direction to disable
      // Eg. 'y' would only allow panning in the y direction
      mode: "xy"
      // Function called once panning is completed
      // Useful for dynamic data loading

    },

    // Container for zoom options
    zoom: {
      // Boolean to enable zooming
      enabled: true,

      // Enable drag-to-zoom behavior
      drag: false,

      // Drag-to-zoom rectangle style can be customized
      // drag: {
      //    borderColor: 'rgba(225,225,225,0.3)'
      //    borderWidth: 5,
      //    backgroundColor: 'rgb(225,225,225)'
      // },

      // Zooming directions. Remove the appropriate direction to disable
      // Eg. 'y' would only allow zooming in the y direction
      mode: "xy"
      // Function called once zooming is completed
      // Useful for dynamic data loading

    }
    //---------------------------------------
  }
};

export const tooltiplist: any = {
  1: '<b>*</b> Experiment with the <b><span style="font-size:4.5vw">Δ</span></b> function and strategize a tactic to compute <b><u>666</u></b> using it',
  2: '<b>*</b> The function of the <b><span style="font-size:4.5vw">Δ</span></b> operator changes each level, becoming more complex',
  3: "<b>*</b> The <b>±</b> key allows you to toggle negation. Input negative numbers, negate outputs, or both",
  4: "<b>*</b> Memory Keys: <b>M1</b>, <b>M2</b> and <b>M3</b> save and recall your output and function usage",
  5: '<b>*</b> The <b><span style="font-size:4.5vw">Δ</span></b> function can be used many times in succession, taking its input recursively',
  6: "<b>*</b> Use the <b>graph</b> view to help identify patterns in more obscure functions",
  7: "<b>*</b> Older functions are often re-used and placed in new, more challenging contexts",
  8: "<b>*</b> Functions are not necessarily algebraic in nature and can be highly deceptive",
  9: '<b>*</b> <b><span style="font-size:4.5vw">Δ</span></b> can treat its input conditionally based on <u>odd</u> critera, obscuring patterns',
  10: "<b>*</b> By holding down the <b>C</b> button you can clear your history and graph data",
  // -------->--------
  //11: "",
  11: "<b>*</b> The <b>help</b> view is different for each level. Consult often for tips and hints <b>©</b>",
  12: "<b>*</b> Hold down any memory key, <b>M1</b>, <b>M2</b> or <b>M3</b>, to overwrite and re-use it",
  13: "<b>*</b> Taking notes or consulting an unpossessed calculator can help - <u>tap and hold the screen</u> to open the desmos calc",
  14: "<b>*</b> Trial and error can work in the short-term, but understanding each level mechanically is requiste for later success",
  15: "<b>*</b> If unsure about the workings of a past level, you can <b>replay</b> it using the graph menu",
  16: "<b>*</b> New obstacles can entirely change how an old problem needs to be approached",
  17: "<b>*</b> Levels can be extremely challenging. You can always skip (after getting a hint) and come back later",
  18: '<b>*</b> <b><span style="font-size:4.5vw">ψ</span></b> is a binary function that forks two numerical inputs',
  19: '<b>*</b> For results of <b><span style="font-size:4.5vw">ψ</span></b> to be graphed, both inputs must be the same',
  20: '<b>*</b> Like unary functions, <b><span style="font-size:4.5vw">ψ</span></b> can perform abstract, non or semi-algebraic operations',

  //22:'<b>*</b> One of the most important tools at your disposal is Wolfram Alpha, its use is encouraged',
  21: '<b>*</b> Wolfram Alpha will provide a list of integer solutions to multivariate equations if you use the "over the integers" flag i.e. "a*b=666 over the integers"',
  22: '<b>*</b> Using multiple instances of the <b><span style="font-size:4.5vw">ψ</span></b> function is often required',
  23: '<b>*</b> Wolfram Alpha\'s "Over the Integers" can save you many hours of tedious algebra and guesswork. i.e. "2a+5b=666 over the integers"',
  //23:'<b>*</b> "Sometimes a function\'s inputs can represent as a range of values, considering the integers between',

  24: '<b>*</b> <b><span style="font-size:4.5vw">ψ</span></b> is not necessarily commutative, i.e. a<b><span style="font-size:4.5vw">ψ</span></b>b is not does not necessarily equal b<b><span style="font-size:4.5vw">ψ</span></b>a',
  25: "<b>*</b> Want to mute the game? Hold down the negation button to toggle SFX",
  26: "<b>*</b> <u>tap and hold the screen</u> to launch your upgraded desmos calculator",
  27: "<b>*</b> Sometimes a function's inputs can represent as a range of values, considering the integers between",
  28: '<b>*</b> Formulas resolve left to right, by function: i.e. X<b><span style="font-size:4.5vw">ψ</span></b>y<b><span style="font-size:4.5vw">ψ</span></b>z = (X<b><span style="font-size:4.5vw">ψ</span></b>y)<b><span style="font-size:4.5vw">ψ</span></b>z',
  29: '<b>*</b> "For additional assistance and tips, click the help view - it changes <u>every level</u>',

  37: '<b>*</b> Use both <b><span style="font-size:4.5vw">Δ</span></b> and <b><span style="font-size:4.5vw">ψ</span></b> <u>together</u> to calculate 666',
  38: '<b>*</b> If you use <b><span style="font-size:4.5vw">Δ</span></b> after a completed binary function, it will apply parantheses',
  39: "<b>*</b> Parantheses are critical to the order of operations and are added automatically",
  40: "<b>*</b> To re-consult the visual slideshow examples for each operator, <u>hold its button down</u>",
  41: "<b>*</b> Memory Keys: <b>M1</b>, <b>M2</b> and <b>M3</b> become especially useful with multiple functions",

  51: '<b>*</b> The <b><span style="font-size:4.5vw">φ</span></b> function returns the index of a recognized integer sequence',
  52: '<b>*</b> The On-Line Encyclopedia of Integer Sequences (OEIS) can be extremely helpful in identifying <b><span style="font-size:4.5vw">φ</span></b>',
  53: '<b>*</b> There is now a shortcut in the "notes" menu for OEIS<b><span style="font-size:4.5vw">φ</span></b>',
  60: '<b>*</b> Use all three functions, <b><span style="font-size:4.5vw">Δ</span></b>, <b><span style="font-size:4.5vw">ψ</span></b> and <b><span style="font-size:4.5vw">φ</span></b> <u>together</u> to calculate 666',
  61: '<b>*</b> Congratulations! You have now unlocked the ability to create levels in the "graph" view'
};

export const mathfacts: any = [
  "100 is the smallest number whose common logarithm is a prime number",
  "1001 is the smallest palindromic product of 3 consecutive primes",
  "1008 is the number of symmetric ways to fold a strip of 16 stamps",
  "101 is the sum of five consecutive primes (13 + 17 + 19 + 23 + 29)",
  "1015 is the number of chiral invertible knots with 12 crossings",
  "1017 is the smallest number whose square contains 7 different digits",
  "102 is an abundant number and semiperfect number",
  "1031 is the length of the largest repunit that is known to be prime",
  "1037 is a value of n for which f(n) = f(n-1) + f(n-2)",
  "1046 is the smallest number whose cube contains 4 consecutive 4's",
  "105 is a triangular number, a 12-gonal number and a Zeisel number",
  "1051 is the smallest value of n for which p(8n) = n",
  "1066 is a value of n for which 2f(n) = f(n+1)",
  "1078 is the number of lattices on 9 unlabeled nodes",
  "108 is the hyperfactorial of 3 since it is of the form ",
  "1081 is a triangular number that is the product of two primes",
  "1086 is the number of 13-hexes with reflectional symmetry",
  "1092 is the order of a non-cyclic simple group",
  "1095 is the number of vertices in a Sierpinski triangle of order 6",
  "11 is the largest known multiplicative persistence",
  "1102 is the number of connected graphs with 10 vertices and 36 edges",
  "1103 is the number of graphs with 9 vertices and 8 edges",
  "111 is also the magic constant of the n-Queens Problem for n = 6",
  "1113 is the number of partitions of 40 into distinct parts",
  "1115 is a number n for which f(n) is a repdigit",
  "1119 is the number of bipartite graphs with 9 vertices",
  "112 is an abundant number and a heptagonal number",
  "113 is a highly cototient number and a centered square number",
  "1132 is the number of 3-valent trees with 15 vertices",
  "1134 is the number of permutations of 9 items that fix 5 elements",
  "1144 is the number of non-invertible knots with 12 crossings",
  "1147 is the product of two consecutive primes",
  "1148 is the number of ways to fold a strip of 9 stamps",
  "115 is a heptagonal pyramidal number and a lucky number",
  "115 is the number of rooted trees with 8 vertices",
  "1150 is the number of 11-iamonds without bilateral symmetry",
  "1155 is the Stirling number of the second kind S(11,9)",
  "1161 is the number of 11-iamonds without holes",
  "1168 is the number of binary cube-free words of length 16",
  "1169 is the number of connected graphs with 8 vertices and 12 edges",
  "1179 is the number of different permanents of binary 7×7 matrices",
  "1189 is the square root of a triangular number",
  "1191 is the number of symmetric plane partitions of 25",
  "1192 is the number of 12-iamonds that do not tile the plane",
  "1204 is the magic constant for a 7×7×7 magic cube",
  "1205 is the number of fullerenes with 58 carbon atoms",
  "1207 is the product of two primes which are reverses of each other",
  "1223 is the smallest number with complexity 24",
  "1232 is (7 × 8 × 9 × 10 × 11) / (7 + 8 + 9 + 10 + 11) ",
  "1234 is the smallest 4-digit number with increasing digits",
  "1249 is the number of simplicial polyhedra with 11 vertices",
  "1257 is a value of n for which f(s(n)) = f(n)",
  "1258 is the number of commutative asymmetric semigroups of order 6",
  "128 is the only 3-digit number that is a 7th power",
  "1288 is the number of possible positions in Othello after 25 moves",
  "1290 is the number of connected graphs with 8 vertices and 16 edges",
  "1293 is a structured truncated tetrahedral number",
  "1294 is the number of 4 dimensional polytopes with 8 vertices",
  "1297 is a Tetranacci-like number starting from 1, 1, 1, and 1",
  "12988816 is the number of domino tilings of an 8×8 checkerboard",
  "130 is the number of functions from 6 unlabeled points to themselves",
  "1303 is the number of multigraphs with 7 vertices and 8 edges",
  "1305 is the number of graphs with 11 vertices and 9 edges",
  "1342 is the smallest number that is 15 away from a prime",
  "136 is the sum of the first 16 positive integers",
  "1369 is a square whose digits are non-decreasing",
  "137 is a strictly non-palindromic number and a primeval number",
  "1378 is the number of symmetric idempotent 6×6 matrices over GF(2)",
  "1379 is the magic constant of a 24×24 magic square",
  "1389 is the number of unit interval graphs with 9 vertices",
  "139 is the number of unlabeled topologies with 5 elements",
  "1405 is the sum of consecutive squares in 2 ways",
  "1411 is the number of quasi-groups of order 5",
  "142 is the number of planar graphs with 6 vertices",
  "143 is the smallest quasi-Carmichael number in base 8",
  "1434 is a number whose sum of squares of the divisors is a square",
  "1438 is the smallest number with complexity 25",
  "1439 is the smallest number with complexity 26",
  "144 is in base 10 a sum-product number, as well as a Harshad number",
  "1441 is a palindrome in base 6 and in base 10",
  "1446 is the number of graphs with 9 vertices and 5 edges",
  "145 is a pentagonal number and a centered square number",
  "1450 is the total number of labeled graphs on 0-5 vertices",
  "1458 is the maximum determinant of a binary 11×11 matrix",
  "1469 is the number of ways to play the first 4 moves in Checkers",
  "1479 is the number of planar partitions of 12",
  "1480 is the number of asymmetric trees with 19 vertices",
  "1481 is a number n for which n, n+2, n+6, and n+8 are all prime",
  "1485 is the number of 3-colored rooted trees with 5 vertices",
  "149 is the smallest number whose square begins with three 2's",
  "1499 is a prime that remains prime if any digit is deleted",
  "150 is a Harshad number and an abundant number",
  "1506 is the sum of its proper divisors that contain the digit 5",
  "1512 is the number of inequivalent Ferrers graphs with 27 points",
  "1514 is a number whose square and cube use different digits",
  "1515 is the number of trees on 15 vertices with diameter 6",
  "1517 is the product of two consecutive primes",
  "1518 is the sum of its proper divisors that contain the digit 5",
  "152 is the sum of four consecutive primes (31 + 37 + 41 + 43)",
  "1525 is a value of n for which s(f(n)) = 2s(n)",
  "154 is the smallest number which is palindromic in bases 6, 8, and 9",
  "1544 is the number of connected 4-regular graphs with 12 vertices",
  "1555 is the largest n so that Q(vn) has class number 4",
  "1561 is the number of series-reduced trees with 19 vertices",
  "157 is the smallest number with f(2n+1) < f(2n)",
  "1582 is a value of n so that n(n+4) is a palindrome",
  "1589 is the starting location of 7777 in the decimal expansion of p",
  "1591 is the sum of the first 13 numbers that have digit sum 13",
  "1595 is the smallest quasi-Carmichael number in base 2",
  "1596 is the sum of the first 15 Fibonacci numbers",
  "1606 is the number of strongly connected digraphs with 4 vertices",
  "1609 is the smallest number whose square contains 4 consecutive 8's",
  "1626 is the number of binary partitions of 31",
  "1630 is the number of 14-ominoes with a line of symmetry",
  "1633 is a number whose square and cube use different digits",
  "1637 is the number of graphs with 9 vertices and 10 edges",
  "1639 is the number of binary rooted trees with 16 vertices",
  "165 is a binary palindromic number (10100101)",
  "166 is a composite number and a Smith number in base 10",
  "1681 is a square and each of its two 2-digit parts is square",
  "1682 is the number of monoids of order 7 with 7 idempotents",
  "1684 is the number of multigraphs with 6 vertices and 9 edges",
  "1690 is the number of ordered sequences of coins totaling 27 cents",
  "1691 is the number of multigraphs with 5 vertices and 11 edges",
  "170 is the smallest number n for which f(n) and s(n) are both square",
  "1700 is the generalized Catalan number C(13,4)",
  "1701 is the Stirling number of the second kind S(8,4)",
  "1705 is the smallest quasi-Carmichael number in base 4",
  "1714 is the number of graphs with 9 vertices and 7 cycles",
  "1725 is a structured deltoidal hexacontahedral number",
  "173 is a square-free number, divisible by no perfect square",
  "173 is an Eisenstein prime with no imaginary part",
  "1730 is the sum of consecutive squares in 2 ways",
  "1738 is 6952 / 4, and this equation uses each digit 1-9 exactly once",
  "174 is an abundant number with the abundance of 12",
  "1764 is the Stirling number of the first kind s(7,2)",
  "177 is a Leyland number since it can be expressed as 27 + 72",
  "1778 is the largest number whose square has 5 digits",
  "1780 is a structured truncated tetrahedral number",
  "1784 is a number n for which f(n) is a repdigit",
  "1798 is a value of n for which f(s(n)) = f(n)",
  "1813 is the number of trees on 15 vertices with diameter 8",
  "1816 is the number of partitions of 44 into distinct parts",
  "1817 is the number of polyominoes with 8 or fewer squares",
  "1825 is the smallest number whose square begins with three 3's",
  "1831 is the smallest prime that is followed by 15 composite numbers",
  "184 is the sum of four consecutive prime numbers (41 + 43 + 47 + 53)",
  "1842 is the number of rooted trees with 11 vertices",
  "1863 is the larger number in a Ruth-Aaron pair",
  "1866 is the number of inequivalent Ferrers graphs with 28 points",
  "187 is the smallest quasi-Carmichael number in base 7",
  "1870 is the product of two consecutive Fibonacci numbers",
  "1871 is a number n for which n, n+2, n+6, and n+8 are all prime",
  "1875 is the smallest order for which there are 21 groups",
  "1880 is a number whose sum of squares of the divisors is a square",
  "1890 is the number of permutations of 10 items that fix 6 elements",
  "1896 is the number of graphs with 9 vertices with clique number 2",
  "1900 is the largest palindrome in Roman numerals",
  "1907 is a value of n for which n (n+2) is a palindrome",
  "1913 is prime and contains the same digits as the next prime",
  "1933 is a prime factor of 111111111111111111111",
  "1942 is the smallest number whose cube contains 5 consecutive 8's",
  "1947 is the number of planar partitions of 16",
  "1957 is the number of permutations of some subset of 6 elements",
  "1964 is the number of legal knight moves in Chess",
  "1980 is the number of ways to fold a 2×4 rectangle of stamps",
  "1995 is the number of graphs with 9 vertices with clique number 6",
  "20 is the number of rooted trees with 6 vertices",
  "2010 is the number of trees on 15 vertices with diameter 7",
  "2017 is a value of n for which f(n) = f(n-1) + f(n-2)",
  "2034 is the number of self-avoiding walks of length 9",
  "2038 is the number of Eulerian graphs with 9 vertices",
  "204 is the square root of a triangular number",
  "2045 is the number of unlabeled partially ordered sets of 7 elements",
  "2052 is the magic constant for a 8×8×8 magic cube",
  "2056 is the magic constant of a 16×16 magic square",
  "2058 is the number of integers with complexity 27",
  "2061 is the number of sets of distinct positive integers with mean 7",
  "2075 is the number of connected graphs with 9 vertices and 11 edges",
  "2082 is the sum of its proper divisors that contain the digit 4",
  "209 is the smallest quasi-Carmichael number in base 9",
  "2090 is the number of possible rows in a 17×17 crossword puzzle",
  "2109 is a value of n so that n(n+7) is a palindrome",
  "2110 is a value of n for which reverse(f(n)) = f(reverse(n))",
  "213 is the number of perfect squared rectangles of order 13",
  "2135 is a value of n for which s(n-1) + s(n+1) = s(2n)",
  "214 is a composite number and a 37-gonal number",
  "2146 is a value of n for which 2f(n) = f(n+1)",
  "2155 is the smallest number whose cube has 10 digits",
  "2161 is a prime factor of 111111111111111111111111111111",
  "2168 is a structured hexagonal diamond number",
  "2176 is the number of prime knots with 12 crossings",
  "218 is the number of digraphs with 4 vertices",
  "2182 is the number of degree 15 irreducible polynomials over GF(2)",
  "2195 is the number of necklaces with 9 beads, each one of 3 colors",
  "2201 is the only non-palindrome known to have a palindromic cube",
  "2209 is a Tribonacci-like number starting from 1, 1, and 1",
  "2219 is the number of 14-hexes with reflectional symmetry",
  "222 is the number of lattices on 8 unlabeled nodes",
  "2221 is a value of n for which s(n) is a repdigit",
  "2226 is the smallest number whose cube contains 4 consecutive 9's",
  "223 is the fourth Carol number and the third to be prime",
  "2235 is a value of n so that n(n+8) is a palindrome",
  "2239 is a prime that remains prime if any digit is deleted",
  "2244 is the generalized Catalan number C(14,4)",
  "225 is the sum of four consecutive primes (47 + 53 + 59 + 61)",
  "2272 is the number of graphs on 7 vertices with no isolated vertices",
  "2273 is the number of functional graphs on 10 vertices",
  "2274 is the sum of its proper divisors that contain the digit 7",
  "228 is the sum of four consecutive primes (47 + 53 + 59 + 61)",
  "2291 is the number of inequivalent Ferrers graphs with 29 points",
  "2293 is a prime that remains prime if any digit is deleted",
  "2296 is a structured great rhombicubeoctahedral number",
  "2297 is the number of inequivalent binary linear codes of length 10",
  "2299 is the number of ordered sequences of coins totaling 28 cents",
  "230 is the number of space groups, including handedness",
  "2303 is a number whose square and cube use different digits",
  "2304 is the number of edges in a 9 dimensional hypercube",
  "2309 is the largest prime factor of 2 × 3 × 5 × 7 × 11 - 1",
  "2312 is the number of series-reduced planted trees with 10 leaves",
  "2318 is the number of connected planar graphs with 10 edges",
  "2322 is the number of connected graphs with 10 edges",
  "233 is the 13th Fibonacci number, being the sum of 89 and 144",
  "2344 is the number of necklaces with 7 beads, each one of 4 colors",
  "2350 is the number of quasi-triominoes that fit inside a 11×11 grid",
  "2351 is a member of the Fibonacci-type sequence starting with 2 and 5",
  "2376 is a structured truncated tetrahedral number",
  "238 is the number of connected partial orders on 6 unlabeled elements",
  "2387 is a structured rhombic triacontahedral number",
  "2388 is the number of 3-connected graphs with 8 vertices",
  "2410 is the number of 3-valent trees with 16 vertices",
  "241e+31 is the partition of a set of 1000 elements",
  "2420 is the number of possible rook moves on a 11×11 chessboard",
  "243 is the largest 3-digit number that is a fifth power (35)",
  "2431 is the Stirling number of the second kind S(13,11)",
  "2434 is the number of legal king moves in Chess",
  "2464 is the number of permutations of 8 items that fix 3 elements",
  "2485 is the number of planar partitions of 13",
  "2492 is the larger number in a Ruth-Aaron pair",
  "2495 is the number of 13-iamonds that tile the plane",
  "2500 is a Tetranacci-like number starting from 1, 1, 1, and 1",
  "2520 is the least common multiple of every integer under 10",
  "2520 is the smallest number divisible by 1 through 10",
  "253 is the smallest non-trivial triangular star number",
  "2548 is the generalized Catalan number C(11,5)",
  "2560 is the number of 2×2 singular matrices mod 8",
  "2562 is a structured pentakis dodecahedral number",
  "2573 is the number of partitions of 35 that do not contain 1 as a part",
  "258 is a value of n so that n(n+9) is a palindrome",
  "2582 is the smallest number whose square begins with four 6's",
  "2583 is the sum of the first 16 Fibonacci numbers",
  "2587 is a value of n for which f(n) + f(n+1) divides s(n) + s(n+1)",
  "2590 is the number of partitions of 47 into distinct parts",
  "2606 is the number of polyhedra with 9 vertices",
  "2609 is the number of perfect squared rectangles of order 15",
  "2615 is the number of functions from 9 unlabeled points to themselves",
  "2616 is the number of graphs with 9 vertices and 6 cycles",
  "2624 is the maximum number of pieces a torus can be cut into with 24 cuts",
  "263 is the largest known prime whose square is strobogrammatic",
  "2635 is the number of necklaces with 6 beads, each one of 5 colors",
  "2636 is a non-palindrome with a palindromic square",
  "2637 is the number of commutative monoids of order 7",
  "264 is the largest known number whose square is undulating",
  "2646 is the Stirling number of the second kind S(9,6)",
  "2651 is the number of asymmetric trees with 12 vertices",
  "266 is the Stirling number of the second kind S(8,6)",
  "2676 is a number n for which f(n) is a repdigit",
  "2678 is the number of connected graphs with 10 vertices and 11 edges",
  "2682 is a number n for which f(n) is a repdigit",
  "2683 is the largest n so that Q(vn) has class number 5",
  "2692 is the sum of the squares of 4 consecutive primes",
  "271 is the smallest prime p so that p-1 and p+1 are divisible by cubes",
  "271 is the sum of the coprime counts for the first 29 integers is 270",
  "2712 is the number of 12-ominoes that tile the plane by translation",
  "2717 is the number of 9-hexes that do not tile the plane",
  "2733 is the number of possible positions in Checkers after 5 moves",
  "274 is the Stirling number of the first kind s(6,2)",
  "275 is the sum of the coprime counts for the first 29 integers is 270",
  "2751 is the number of ordered partitions of 21 into distinct parts",
  "277 is the fifty-ninth prime number, following 271 and preceding 281",
  "2787 is a value of n for which the first n binary digits of p form a prime",
  "28 is the ninth and last number in early Indian magic square of order 3",
  "2806 is the number of semigroups of order 6 with 2 idempotents",
  "2811 is the number of inequivalent Ferrers graphs with 30 points",
  "2817 is a member of the Fibonacci-type sequence starting with 1 and 4",
  "2824 is the smallest number whose cube contains six 2's",
  "2828 is a value of n so that n(n+8) is a palindrome",
  "2844 is the sum of the first 15 numbers that have digit sum 15",
  "2848 is the smallest number whose square contains 4 consecutive 1's",
  "285 is the number of binary rooted trees with 13 vertices",
  "287 is the sum of consecutive primes in 3 different ways",
  "2874 is the number of multigraphs with 5 vertices and 12 edges",
  "2878 is the number of integers with complexity 28",
  "2879 is the smallest number with complexity 27",
  "2888 is the first of five consecutive squareful numbers",
  "2893 is the number of planar 2-connected graphs with 8 vertices",
  "2895 is the smallest n for which 38n contains only 0's and 1's",
  "2900 is the number of self-avoiding walks in a quadrant of length 10",
  "2910 is the number of partitions of 48 into distinct parts",
  "2911 is a value of n for which s(n-1) = s(n+1)",
  "2913 is a value of n for which s(n-1) + s(n+1) = s(2n)",
  "2914 is a value of n for which s(n-1) = s(n+1)",
  "292 is the number of ways to make change for a dollar",
  "2922 is the sum of its proper divisors that contain the digit 4",
  "2931 is the number of trees on 16 vertices with diameter 6",
  "2933 is a value of n for which s(f(n)) = 2s(n)",
  "2938 is the number of binary rooted trees with 17 vertices",
  "294 is the number of planar 2-connected graphs with 7 vertices",
  "295 is a structured deltoidal hexacontahedral number",
  "2953 is the smallest number whose cube contains six 7's",
  "296 is the number of partitions of 30 into distinct parts",
  "2971 is the index of a prime Fibonacci number",
  "2988 is the number of series-reduced trees with 20 vertices",
  "299 is the maximum number of regions a cube can be cut into with 12 cuts",
  "3 is the first odd prime number, and the second smallest prime",
  "3008 is the number of symmetric plane partitions of 29",
  "3012 is the sum of its proper divisors that contain the digit 5",
  "3016 is a value of n for which n f(n) is a palindrome",
  "3026 is the number of 10-ominoes that tile the plane isohedrally",
  "3032 is the number of trees on 19 vertices with diameter 5",
  "3036 is the sum of its proper divisors that contain the digit 5",
  "3056 is a structured snub dodecahedral number",
  "3057 is the number of rooted ternary trees with 12 vertices",
  "3058 is the number of 7-digit triangular numbers",
  "3068 is the number of 10-ominoes that tile the plane",
  "307 is a non-palindrome with a palindromic square",
  "3070 is the number of paraffins with 9 carbon atoms",
  "3072 is the smallest number with exactly 22 divisors",
  "3074 is the number of binary partitions of 37",
  "3089 is the smallest prime so that it and the next 2 primes all end in 9",
  "3092 is a structured truncated tetrahedral number",
  "3094 is 21658 / 7, and each digit is contained in the equation exactly once",
  "31 is a repdigit in base 5 (111), and base 2 (11111)",
  "3105 is a member of the Fibonacci-type sequence starting with 2 and 7",
  "3120 is the product of the first 6 Fibonacci numbers",
  "3126 is a Sierpinski Number of the First Kind",
  "3127 is the product of two consecutive primes",
  "3136 is a square that remains square if all its digits are decremented",
  "3146 is a structured deltoidal hexacontahedral number",
  "3156 is the sum of its proper divisors that contain the digit 5",
  "3161 is the smallest number whose square begins with three 9's",
  "3162 is the largest number whose square has 6 digits",
  "3163 is the smallest number whose square has 7 digits",
  "3171 is the sum of the squares of 3 consecutive primes",
  "3174 is the first of four consecutive squareful numbers",
  "3179 is the number of 13-ominoes that tile the plane by translation",
  "318 is the number of unlabeled partially ordered sets of 6 elements",
  "3191 is the smallest number whose reciprocal has period 29",
  "320 is the maximum determinant of a binary 10×10 matrix",
  "3206 is the smallest number whose square contains 8 different digits",
  "3210 is the smallest 4-digit number with decreasing digits",
  "3225 is the number of symmetric 3×3 matrices in base 5 with determinant 0",
  "3226 is the number of 12-iamonds without holes",
  "324 is the largest possible product of positive integers with sum 16",
  "3247 is the number of connected graphs with 9 vertices and 25 edges",
  "3248 is the number of legal bishop moves in Chess",
  "3251 is a number n for which n, n+2, n+6, and n+8 are all prime",
  "3252 is the number of graphs with 9 vertices and 11 edges",
  "325e+32 is the last known power of two not containing the digit 9",
  "326 is the number of permutations of some subset of 5 elements",
  "3264 is the number of partitions of 49 into distinct parts",
  "3265 is the smallest n for which 34n contains only 0's and 1's",
  "3281 is the sum of consecutive squares in 2 ways",
  "3282 is the sum of its proper divisors that contain the digit 4",
  "3285 is the magic constant for a 9×9×9 magic cube",
  "329 is the number of forests with 10 vertices",
  "3292 is the number of ways to tile a 4×27 rectangle with 4×1 rectangles",
  "3295 is the number of self-dual binary codes of length 32",
  "33 is the largest number that is not a sum of distinct triangular numbers",
  "3300 is the number of groupoids on 4 elements",
  "3302 is the maximum number of pieces a torus can be cut into with 26 cuts",
  "3304 is the maximum number of regions a cube can be cut into with 27 cuts",
  "331 is both a centered pentagonal number and a centered hexagonal number",
  "3313 is the smallest prime number where every digit d occurs d times",
  "3331 is the number of monoids of order 7 with 3 idempotents",
  "3335 is the smallest number whose square contains 4 consecutive 2's",
  "3338 is a member of the Fibonacci-type sequence starting with 3 and 7",
  "334 is the number of trees on 13 vertices with diameter 7",
  "3361 is the number of quasi-triominoes that fit inside a 12×12 grid",
  "3379 is a number whose square and cube use different digits",
  "3381 is the number of ways to 14-color the faces of a tetrahedron",
  "3382 is a value of n for which 2f(n) = f(n+1)",
  "339 is the number of ways to divide 5 black and 5 white beads into piles",
  "3403 is a triangular number that is the product of two primes",
  "3404 is the number of binary partitions of 38",
  "3405 is a structured great rhombicosidodecahedral number",
  "342 is the number of inequivalent binary linear codes of length 8",
  "3427 is a member of the Fibonacci-type sequence starting with 1 and 5",
  "3431 is the number of inequivalent Ferrers graphs with 31 points",
  "3461 is a number n for which n, n+2, n+6, and n+8 are all prime",
  "35 is a centered cube number, a pentagonal number and a pentatope number",
  "35 is the highest number one can count to on one's fingers using base 6",
  "350 is the Stirling number of the second kind S(7,4)",
  "3522 is the sum of its proper divisors that contain the digit 7",
  "3527 is the number of ways to fold a strip of 10 stamps",
  "3534 is the number of 5-step self-avoiding walks on the cubic lattice",
  "3541 is the smallest number whose reciprocal has period 20",
  "355 is the number of labeled topologies with 4 elements",
  "3552 is a value of n for which n f(n) is a palindrome",
  "3570 is both a triangular number and 6 times a triangular number",
  "3575 is the smallest n for which 28n contains only 0's and 1's",
  "3581 is the smallest n for which 31n contains only 0's and 1's",
  "3583 is the smallest number requiring an addition chain of length 16",
  "358833097 is the number of stellations of the rhombic triacontahedron",
  "36 is the smallest non-trivial number which is both square and triangular",
  "3609 is the number of multigraphs with 22 vertices and 4 edges",
  "361 is the number of intersections on a Go board",
  "3626 is a member of the Fibonacci-type sequence starting with 1 and 9",
  "3645 is the maximum determinant of a binary 12×12 matrix",
  "3655 is the sum of consecutive squares in 2 ways",
  "3658 is the number of forests with 13 vertices",
  "3663 is a palindrome in base 8 and in base 10",
  "367 is the largest number whose square has strictly increasing digits",
  "368 is the number of ways to tile a 4×15 rectangle with the pentominoes",
  "3681 is the maximum number of pieces a torus can be cut into with 27 cuts",
  "3690 is the number of trees on 29 vertices with diameter 4",
  "37 is a factor of all 3-digit base 10 repdigits, such as 111",
  "3705 is the generalized Catalan number C(16,4)",
  "3711 is the number of multigraphs with 6 vertices and 10 edges",
  "3714 is the number of graphs with 8 vertices and edge-connectivity 1",
  "3715 is a member of the Fibonacci-type sequence starting with 3 and 8",
  "3721 is the number of partitions of 46 in which no part occurs only once",
  "3734 is the number of binary partitions of 39",
  "3740 is the sum of consecutive squares in 2 ways",
  "3743 is the number of polyaboloes with 9 half squares",
  "3750 is the first of four consecutive squareful numbers",
  "3761 is the first year of the modern Hebrew calendar",
  "3762 is the number of bicentered trees with 15 vertices",
  "3763 is the largest n so that Q(vn) has class number 6",
  "3765 is the number of series-reduced planted trees with 18 vertices",
  "3767 is the smallest number with complexity 28",
  "3773 is a structured great rhombicubeoctahedral number",
  "3777 is a Pentanacci-like number starting from 1, 1, 1, 1, and 1",
  "378 is the maximum number of regions a cube can be cut into with 13 cuts",
  "3791 is the number of symmetric plane partitions of 30",
  "3803 is the largest prime factor of 123456789",
  "3804 is a member of the Fibonacci-type sequence starting with 2 and 5",
  "3808 is the generalized Catalan number C(12,5)",
  "382 is the smallest number n with s(n) = s(n+3)",
  "3829 is the sum of the first 16 numbers that have digit sum 16",
  "3834 is the number of weakly connected directed graphs with 4 vertices",
  "3836 is the maximum number of inversions in a permutation of length 7",
  "3846 is the number of Hamiltonian cycles of a 4×11 rectangle graph",
  "3850 is a structured octagonal anti-diamond number",
  "3859 is a member of the Fibonacci-type sequence starting with 2 and 9",
  "387 is the smallest number with sort-then-add persistence of 10",
  "3871 is the sum of the cubes of 3 consecutive primes",
  "3882 is the sum of its proper divisors that contain the digit 4",
  "3883 is the smallest number whose cube contains 4 consecutive 6's",
  "3893 is the number of 3-regular connected planar graphs with 18 vertices",
  "390 is the number of partitions of 32 into distinct parts",
  "3907 is 15628 / 4, and each digit is contained in the equation exactly once",
  "3929 is the number of integers with complexity 29",
  "3939 is a structured truncated tetrahedral number",
  "3979 is the number of centered trees with 15 vertices",
  "398 is the number of integers with complexity 22",
  "3991 is the number of labeled graded partially ordered sets with 5 elements",
  "3994 is the number of transitive relations on 4 labeled nodes",
  "40 is the number of n-queens problem solutions for n = 7",
  "40 is the only number whose letters are in alphabetical order",
  "4010 is the magic constant of a 20×20 magic square",
  "4011 is the sum of the squares of 3 consecutive primes",
  "4013 is a prime factor of 1111111111111111111111111111111111",
  "402 is the number of graphs with 8 vertices and 9 edges",
  "4031 is the sum of the cubes of the first 6 primes",
  "4032 is the number of connected bipartite graphs with 10 vertices",
  "4037 is a member of the Fibonacci-type sequence starting with 1 and 6",
  "4051 is the number of partitions of 6 items into ordered lists",
  "4055 is the smallest number whose cube contains six 6's",
  "4056 is the number of possible rook moves on a 13×13 chessboard",
  "406 is the number of ways to tile a 3×17 rectangle with 3×1 rectangles",
  "4063 is a Tribonacci-like number starting from 1, 1, and 1",
  "4074 is a value of n for which s(n) = 2reverse(n)",
  "4086 is a permutation of the sum of its proper divisors",
  "4087 is the product of two consecutive primes",
  "409 is the number of graphs with 8 vertices with clique number 2",
  "4093 is 28651 / 7, and each digit is contained in the equation exactly once",
  "4122 is the number of labeled monoids of order 5 with fixed identity",
  "4124 is the number of binary partitions of 40",
  "4132 is the number of connected 3-regular bipartite graphs with 22 vertices",
  "4147 is a value of n for which f(n) = f(reverse(n))",
  "4163 is the number of inequivalent asymmetric Ferrers graphs with 32 points",
  "4180 is the sum of the first 17 Fibonacci numbers",
  "4185 is the smaller number in a Ruth-Aaron pair",
  "4186 is a hexagonal, 13-gonal, triangular number",
  "4188 is a value of n for which s(n-1) = s(n+1)",
  "4191 is the number of graphs with 12 vertices and 10 edges",
  "4196 is the number of 3-regular bipartite graphs with 22 vertices",
  "420 is the smallest number divisible by 1 through 7",
  "4210 is the number of graphs with 10 vertices with clique number 7",
  "4222 is the number of 13-hexes with bilateral symmetry",
  "4224 is a palindrome that is one less than a square",
  "423 is a number that does not have any digits in common with its cube",
  "4231 is the number of labeled partially ordered sets with 5 elements",
  "4244 is the total number of digits in all the 4-digit primes",
  "4252 is the smallest number in base 8 to have 5 different digits",
  "4260 is a value of n for which n+1, 2n+1, 3n+1, and 4n+1 are all prime",
  "4264 is a number whose sum of squares of the divisors is a square",
  "4279 is the smallest semiprime super Catalan number",
  "4285 is a structured hexagonal diamond number",
  "4297 is the smallest prime that is followed by 29 composite numbers",
  "43 is the largest natural number that is not an (original) McNugget number",
  "4325 is a member of the Fibonacci-type sequence starting with 4 and 9",
  "4330 is the number of 4-regular multigraphs with 10 vertices",
  "4337 is a value of n for which f(n) = f(n-1) + f(n-2)",
  "434 is the smallest composite value of n for which s(n) + 2 = s(n+2)",
  "435 is the number of ordered partitions of 16 into distinct parts",
  "436 is the smallest number whose cube contains four 8's",
  "4382 is the number of primitive sorting networks on 9 elements",
  "4396 is 157 × 28 and each digit is contained in the equation exactly once",
  "440 is the number of permutations of 12 items that fix 9 elements",
  "441 is the smallest square which is the sum of 6 consecutive cubes",
  "4431 is the number of graphs with 8 vertices that have 2 automorphisms",
  "4434 is the sum of its proper divisors that contain the digit 7",
  "4438 is the number of 15-hexes with reflectional symmetry",
  "4441 is the number of different solutions to ±1±2±18 = 1",
  "4442 is a value of n for which s(n) is a repdigit",
  "4460 is the number of 10-ominoes without holes",
  "4461 is the number of asymmetrical 10-ominoes",
  "4473 is a value of n for which s(n) = 2reverse(n)",
  "4478 is the number of fullerenes with 66 carbon atoms",
  "4489 is a square whose digits are non-decreasing",
  "4502 is the number of unit interval graphs with 10 vertices",
  "4536 is the Stirling number of the first kind s(9,6)",
  "4542 is the number of trees on 20 vertices with diameter 5",
  "4548 is the sum of its proper divisors that contain the digit 7",
  "4550 is the Stirling number of the second kind S(15,13)",
  "458 is a number that does not have any digits in common with its cube",
  "4582 is the number of partitions of 52 into distinct parts",
  "4615 is a value of n for which s(f(n)) = 2s(n)",
  "4622 is the number of 12-ominoes that contain 1 hole",
  "4625 is the number of trees on 16 vertices with diameter 7",
  "4642 is the smallest number whose cube has 11 digits",
  "4657 is a number that does not have any digits in common with its cube",
  "4663 is the number of 12-ominoes that contain holes",
  "4666 is the number of tilted rectangles with vertices in a 13×13 grid",
  "4672 is a permutation of the sum of its proper divisors",
  "4683 is the number of orderings of 6 objects with ties allowed",
  "4698 is the smallest number so that it and its reverse are divisible by 54",
  "4705 is the sum of consecutive squares in 2 ways",
  "4709 is the number of symmetric plane partitions of 31",
  "472 is the number of ways to tile a 5×5 square with integer-sided squares",
  "4723 is the index of a prime Fibonacci number",
  "4726 is the smallest number whose cube contains 5 consecutive 5's",
  "4730 is the number of multigraphs with 5 vertices and 13 edges",
  "4751 is the starting location of 8888 in the decimal expansion of p",
  "4757 is the number of ordered partitions of 23 into distinct parts",
  "4760 is the sum of consecutive squares in 2 ways",
  "4766 is the number of rooted trees with 12 vertices",
  "4776 is a structured pentagonal hexacontahedral number",
  "479 is the number of sets of distinct positive integers with mean 6",
  "48 is the smallest number with exactly ten divisors",
  "4807 is the smallest quasi-Carmichael number in base 10",
  "483 is the last 3-digit string in the decimal expansion of p",
  "4832 is a number whose square contains the same digits",
  "4848 is the number of quaternary square-free words of length 8",
  "485 is the number of categories with 6 morphisms and 2 objects",
  "4852 is the sum of the squares of 4 consecutive primes",
  "4866 is the number of partitions of 48 in which no part occurs only once",
  "4875 is the number of graphs with 10 vertices and 3 cycles",
  "4878 is the number of alternating knots with 13 crossings",
  "4879 is 238 + 0 + 4641 and has the square 23804641",
  "4895 is the product of two consecutive Fibonacci numbers",
  "4899 is the sum of the squares of 3 consecutive primes",
  "49 is the square of seven and is therefore the fourth squared prime number",
  "49000000000000000 is the fifth taxicab number",
  "4902 is the starting location of 2222 in the decimal expansion of p",
  "4928 is a structured truncated tetrahedral number",
  "494 is the number of unlabeled distributive lattices with 14 elements",
  "4944 is a value of n for which n f(n) is a palindrome",
  "495 is the Kaprekar constant for 3-digit numbers",
  "4950 is both a triangular number and 5 times a triangular number",
  "4961 is a Hexanacci-like number starting from 1, 1, 1, 1, 1, and 1",
  "4964 is the number of binary partitions of 42",
  "5000 is the largest number whose English name does not repeat any letters",
  "5000000000000 is the number of known digits of pi of 2010",
  "5005 is the smallest palindromic product of 4 consecutive primes",
  "501 is the number of partitions of 5 items into ordered lists",
  "5024 is a member of the Fibonacci-type sequence starting with 2 and 7",
  "5026 is the number of connected graphs with 11 vertices and 1 cycle",
  "5039 is the number of planar partitions of 18",
  "5048 is the number of strongly connected digraphs with 5 vertices",
  "5059 is the number of inequivalent asymmetric Ferrers graphs with 33 points",
  "507 is the number of rooted ternary trees with 10 vertices",
  "5071 is a Lucas 3-step number and a Lucas 4-step number",
  "5080 is a structured truncated octahedral number",
  "5084 is the number of inequivalent Ferrers graphs with 33 points",
  "5096 is the number of possible rook moves on a 14×14 chessboard",
  "510 is the number of binary rooted trees with 14 vertices",
  "5120 is the number of edges in a 10 dimensional hypercube",
  "5130 is a value of n for which f(n) and s(n) are square",
  "5141 is the only four digit number that is reversed in hexadecimal",
  "5142 is the sum of its proper divisors that contain the digit 7",
  "515 is the number of graphs on 6 vertices with no isolated vertices",
  "5170 is the number of partitions of 39 that do not contain 1 as a part",
  "5181 is a structured octagonal anti-diamond number",
  "5185 is the number of 2×2 singular matrices mod 17",
  "5186 is equal to the sum of its anti-divisors",
  "519 is the number of trees on 15 vertices with diameter 5",
  "5191 is a value of n for which s(n+1) = 2s(n)",
  "523 is the smallest prime that is followed by 17 composite numbers",
  "5241 is the starting location of 7777 in the decimal expansion of p",
  "5244 is the sum of consecutive squares in 2 ways",
  "5250 is the number of linear geometries on 10 unlabeled points",
  "5256 is the number of labeled partially ordered sets of 4 elements",
  "5269 is the number of binary rooted trees with 18 vertices",
  "5274 is the sum of its proper divisors that contain the digit 7",
  "5289 is a structured rhombic triacontahedral number",
  "5292 is 28 + 0 + 0 + 5264 and has square 28005264",
  "53 is the only two digit number that is reversed in hexadecimal",
  "5313 is the index of a triangular number containing only 3 different digits",
  "5324 is the number of binary cube-free words of length 20",
  "533 is the number of degree sequences for graphs with 5 vertices",
  "5335 is the magic constant of a 22×22 magic square",
  "5346 is 198 × 27 and each digit is contained in the equation exactly once",
  "536 is the number of solutions of the stomachion puzzle",
  "5366 is the number of graphs with 8 vertices that have chromatic number 4",
  "5387 is the index of a prime Fibonacci number",
  "539 is the number of multigraphs with 5 vertices and 9 edges",
  "5390 is the number of ways to 7-color the faces of a cube",
  "5405 is the smaller number in a Ruth-Aaron pair",
  "5412 is a value of n so that n(n+4) is a palindrome",
  "542 is a member of the Fibonacci-type sequence starting with 3 and 8",
  "5422 is the number of semigroups of order 6 with 3 idempotents",
  "544 is the generalized Catalan number C(14,3)",
  "5443 is the smallest prime p with 17 consecutive quadratic residues mod p",
  "5460 is both a triangular number and 7 times a triangular number",
  "5479 is the number of bipartite graphs with 10 vertices",
  "5489 is the maximum number of regions a cube can be cut into with 32 cuts",
  "5493 is the number of integers with complexity 30",
  "5499 is the average of all the even 4-digit numbers",
  "5504 is the number of series-parallel networks with 6 labeled edges",
  "5508 is the generalized Catalan number C(13,5)",
  "5513 is the number of self-avoiding walks of length 10",
  "552 is the number of prime knots with 11 crossings",
  "5533 is the number of graphs with 10 vertices and 2 cycles",
  "554 is the number of self-dual planar graphs with 20 edges",
  "5551 is the number of trees on 17 vertices with diameter 6",
  "5574 is the number of trees on 31 vertices with diameter 4",
  "5585 is the number of monoids of order 7 with 2 idempotents",
  "56 is the number of reduced 5×5 Latin squares",
  "5600 is the number of self-complementary graphs with 13 vertices",
  "565 is a structured truncated octahedral number",
  "5651 is a number n for which n, n+2, n+6, and n+8 are all prime",
  "5668 is the number of semigroups of order 6 with 5 idempotents",
  "5670 is a value of n for which f(n) and s(n) are square",
  "5671 is a triangular number that is the product of two primes",
  "5689 is the largest 4-digit prime with strictly increasing digits",
  "5692 is a number that does not have any digits in common with its cube",
  "5696 is the smallest number whose square contains 4 consecutive 4's",
  "57 is the sixteenth discrete semiprime and the sixth in the (3q) family",
  "570 is the product of all the prime palindromic Roman numerals",
  "5709 is a structured pentakis dodecahedral number",
  "5711 is the smallest prime p with 18 consecutive quadratic residues mod p",
  "5717 is a value of n for which the first n binary digits of p form a prime",
  "5718 is the number of partitions of 54 into distinct parts",
  "5721 is the number of graphs with 8 vertices that have chromatic number 3",
  "5731 is a value of n for which n (n+2) is a palindrome",
  "575 is a palindrome that is one less than a square",
  "5767 is the product of two consecutive primes",
  "5775 is the smallest value of n for which both n and n+1 are abundant",
  "578 is the number of graphs with 7 vertices with clique number 3",
  "5796 is 138 × 42 and each digit is contained in the equation exactly once",
  "58 is the number of commutative semigroups of order 4",
  "5813 is the concatenation of 3 consecutive Fibonacci numbers",
  "5817 is 34902 / 6, and each digit is contained in the equation exactly once",
  "582 is the number of antisymmetric relations on a 5 element set",
  "583 is the smallest number whose reciprocal has period 26",
  "585 is a palindrome in base 2, base 8, and in base 10",
  "586 is the smallest number that appears in its factorial 6 times",
  "5863 is the starting location of 7777 in the decimal expansion of p",
  "5867 is a member of the Fibonacci-type sequence starting with 1 and 9",
  "587 is the smallest number whose digit sum is larger than that of its cube",
  "5880 is the Stirling number of the second kind S(10,7)",
  "5896 is the number of ways to tile a 3×24 rectangle with 3×1 rectangles",
  "59 is one of the factors that divides the smallest composite Euclid number",
  "59 is the number of stellations of an icosahedron",
  "590 is a value of n for which f(n) + f(n+1) divides s(n) + s(n+1)",
  "5909 is the number of symmetric plane partitions of 32",
  "5923 is the largest n so that Q(vn) has class number 7",
  "5925 is the index of a triangular number containing only 3 different digits",
  "5929 is a square which is also the sum of 11 consecutive squares",
  "5938 is the number of binary partitions of 44",
  "595 is the number of ways to tile a 3×18 rectangle with 3×1 rectangles",
  "5959 is the smaller number in a Ruth-Aaron pair",
  "596 is the number of Hamiltonian cycles of a 4×9 rectangle graph",
  "5972 is the smallest number that appears in its factorial 8 times",
  "5975 is a value of n for which s(n) = s(reverse(n))",
  "5978 is a value of n where f(n) is the product of the digits of n",
  "599 is the smallest number whose digits add to 23",
  "5994 is the number of lattices on 10 unlabeled nodes",
  "60 is the smallest number divisible by 1 through 6",
  "60 is the smallest number divisible by the numbers 1 to 6",
  "6020 is the number of Hamiltonian graphs with 8 vertices",
  "6070 is a structured truncated tetrahedral number",
  "608 is a number that does not have any digits in common with its cube",
  "6092 is the number of 16-ominoes with a line of symmetry",
  "610 is the smallest Fibonacci number that begins with 6",
  "6102 is the largest number n known where f(n) is the reverse of n",
  "6106 is a value of n for which 2f(n) = f(n+1)",
  "612 is a number whose square and cube use different digits",
  "6142 is the number of inequivalent asymmetric Ferrers graphs with 34 points",
  "6143 is the smallest prime that contains twelve 1's in binary",
  "6155 is a member of the Fibonacci-type sequence starting with 2 and 5",
  "6173 is a prime that remains prime if any digit is deleted",
  "6174 is the Kaprekar constant for 4-digit numbers",
  "6176 is the last 4-digit sequence to appear in the decimal expansion of p",
  "618 is the number of ternary square-free words of length 15",
  "621 is the number of ways to 9-color the faces of a tetrahedron",
  "6237 is a number whose sum of the squares of its divisors is a square",
  "6244 is a member of the Fibonacci-type sequence starting with 2 and 9",
  "6290 is the number of 13-iamonds that do not tile the plane",
  "6293 is the number of ordered partitions of 24 into distinct parts",
  "6307 is the largest n so that Q(vn) has class number 8",
  "6312 is the sum of its proper divisors that contain the digit 5",
  "6332 is the number of fullerenes with 68 carbon atoms",
  "6336 is the number of ways to tile a 9×4 rectangle with 2×1 rectangles",
  "6343 is the number of quasi-triominoes that fit inside a 14×14 grid",
  "6351 is the largest number known that is not the sum of 3 squares or cubes",
  "6378 is the number of partitions of 55 into distinct parts",
  "6389 is the number of functional graphs on 11 vertices",
  "6400 is a square whose digits are non-increasing",
  "646 is the number of connected planar graphs with 7 vertices",
  "6472 is the number of polyominoes with 9 or fewer squares",
  "6487 is the number of partitions of 51 in which no part occurs only once",
  "6489 is half again as large as the sum of its proper divisors",
  "6506 is a value of n for which the first n binary digits of p form a prime",
  "6512 is the number of 11-ominoes that tile the plane isohedrally",
  "6527 is a value of n for which f(n) = f(n-1) + f(n-2)",
  "6552 is the number of different full houses in 5 card poker with one joker",
  "6557 is the product of two consecutive primes",
  "657 is the number of ways to tile a 4×22 rectangle with 4×1 rectangles",
  "6583 is a value of n for which s(f(n)) = 2s(n)",
  "6620 is the number of 11-ominoes that tile the plane",
  "663 is the generalized Catalan number C(15,3)",
  "664 is a value of n so that n(n+7) is a palindrome",
  "6643 is the smallest number which is palindromic in bases 2 and 3",
  "665 is a member of the Fibonacci-type sequence starting with 1 and 4",
  "666 is the largest rep-digit triangular number",
  "6663 is a value of n for which s(n) is a repdigit",
  "6667 is the number of self-dual planar graphs with 24 edges",
  "6668 is the number of trees on 21 vertices with diameter 5",
  "667 is the maximal number of regions into which 36 lines divide a plane",
  "668 is the number of legal pawn moves in Chess",
  "6694 is a value of n for which the sum of the first n primes is square",
  "6706 is the number of Hamiltonian paths in a 8×5 rectangle graph",
  "6728 is the number of domino tilings of a 6×6 square",
  "673 is a Tetranacci-like number starting from 1, 1, 1, and 1",
  "6740 is the number of 13-iamonds that do not tile the plane",
  "675 is the smallest order for which there are 17 groups",
  "6754 is the smallest number in base 9 to have 5 different digits",
  "6757 is the number of connected graphs with 10 vertices and 34 edges",
  "6759 is the number of graphs with 10 vertices and 11 edges",
  "6764 is the sum of the first 18 Fibonacci numbers",
  "6769 is the Stirling number of the first kind s(8,4)",
  "678 is a member of the Fibonacci-type sequence starting with 1 and 7",
  "6788 is the smallest number with multiplicative persistence 6",
  "6789 is the largest 4-digit number with increasing digits",
  "679 is the smallest number with multiplicative persistence 5",
  "6793 is the smallest prime so that it and the next 2 primes all end in 3",
  "68 is the 2-digit string that appears latest in the decimal expansion of p",
  "6816 is the index of a triangular number containing only 3 different digits",
  "6831 is a structured truncated octahedral number",
  "686 is the number of partitions of 35 in which no part occurs only once",
  "6861 is a value of n for which s(n-1) + s(n+1) = s(2n)",
  "6868 is the larger number in a Ruth-Aaron pair",
  "6874 is equal to the sum of its anti-divisors",
  "6886 is a palindrome in base 9 and in base 10",
  "6902 is the number of Hamiltonian paths of a 3×10 rectangle graph",
  "6903 is a value of n for which s(n-1) = s(n+1)",
  "6919 is the number of non-invertible knots with 13 crossings",
  "6924 is the magic constant of a 24×24 magic square",
  "6928 is the number of inequivalent binary linear codes of length 11",
  "6930 is the square root of a triangular number",
  "6935 is the smallest number whose cube contains six 3's",
  "6940 is the sum of its proper divisors that contain the digit 3",
  "6942 is the number of labeled topologies with 5 elements",
  "6944 is the number of degree sequences for graphs with 6 vertices",
  "696 is a palindrome n so that n(n+8) is also palindromic",
  "6972 is the number of possible positions in Checkers containing 2 checkers",
  "697e+40 is the least common multiple of every integer from 1 to 100",
  "6991 is a value of n for which reverse(f(n)) = f(reverse(n))",
  "6996 is a palindrome n so that n(n+8) is also palindromic",
  "7001 is the number of 13-hexes that tile the plane by translation",
  "7003 is the number of graphs with 9 vertices that have 8 automorphisms",
  "7019 is a prime that remains prime if any digit is deleted",
  "7056 is a square that is the product of two triangular numbers",
  "7068 is the number of series-reduced planted trees with 11 leaves",
  "7071 is the smallest number whose square contains 4 consecutive 9's",
  "7072 is the generalized Catalan number C(10,7)",
  "7084 is the generalized Catalan number C(19,4)",
  "709 is the number of connected planar graphs with 9 edges",
  "710 is the number of connected graphs with 9 edges",
  "7108 is the number of partitions of 56 into distinct parts",
  "7123 is the number of 2-connected graphs with 8 vertices",
  "713 is the number of commutative monoids of order 7 with 4 idempotents",
  "716 is the smallest number whose cube contains four 6's",
  "7170 is a value of n for which s(n-1) = s(n+1)",
  "7188 is the number of ways to permute 5 red, 5 white, and 5 blue balls",
  "7225 is the number of ways to 17-color the faces of a tetrahedron",
  "7230 is the sum of consecutive squares in 2 ways",
  "7241 is the number of asymmetric trees with 19 vertices",
  "724e+34 is the number of different positions of Alexander's Star",
  "7254 is 186 × 39 and each digit is contained in the equation exactly once",
  "726 is the number of 4-step self-avoiding walks on the cubic lattice",
  "73 is the largest minimal Primitive root in the first 100000 primes",
  "730 is the number of connected bipartite graphs with 9 vertices",
  "7311 is the number of symmetric plane partitions of 33",
  "7318 is the number of functions from 10 unlabeled points to themselves",
  "7376 is a structured truncated tetrahedral number",
  "74 is the twenty-first distinct semiprime and the eleventh of the form 2×q",
  "740 is the number of self-avoiding walks of length 8",
  "741 is the number of multigraphs with 6 vertices and 8 edges",
  "7413 is the number of even permutations on 8 elements with no fixed points",
  "7420 is the number of permutations of 8 items that fix 2 elements",
  "7427 is the number of inequivalent asymmetric Ferrers graphs with 35 points",
  "7430 is the number of labeled commutative monoids of order 5",
  "7433 is a prime that remains prime if any digit is deleted",
  "7436 is the number of 6×6 alternating sign matrices",
  "744 is the number of perfect squared rectangles of order 14",
  "745 is the smallest number whose square begins with three 5's",
  "7464 is a structured hexagonal diamond number",
  "7473 is a Tribonacci-like number starting from 1, 1, and 1",
  "7488 is (12 × 13 × 14 × 15 × 16) / (12 + 13 + 14 + 15 + 16) ",
  "7494 is the sum of its proper divisors that contain the digit 4",
  "75 is the number of orderings of 4 objects with ties allowed",
  "750 is the Stirling number of the second kind S(10,8)",
  "7512 is the sum of its proper divisors that contain the digit 5",
  "753 is the smallest number whose cube contains 4 consecutive 7's",
  "7546 is the number of series-reduced planted trees with 19 vertices",
  "755 is the number of trees on 14 vertices with diameter 6",
  "7551 is a value of n for which f(n) + f(n+1) divides s(n) + s(n+1)",
  "7557 is a palindrome that is the sum of the first 37 palindromes",
  "757 is the smallest number whose reciprocal has a period of 27",
  "7581 is the number of monotone Boolean functions of 5 variables",
  "7595 is the number of simplicial polyhedra with 12 vertices",
  "760 is the number of partitions of 37 into distinct parts",
  "7615 is a value of n for which s(n+1) = 2s(n)",
  "762 is the starting location of 999999 in the decimal expansion of p",
  "7639 is the number of rooted ternary trees with 13 vertices",
  "764 is the number of 8×8 symmetric permutation matrices",
  "766 is the number of series-reduced planted trees with 9 leaves",
  "7663 is the product of two primes which are reverses of each other",
  "7669 is the number of integers with complexity 31",
  "7680 is the number of possible rook moves on a 16×16 chessboard",
  "769 is the total number of digits of all binary numbers of length 1-7",
  "77 is the number of digits of the 12th perfect number",
  "7710 is the number of degree 17 irreducible polynomials over GF(2)",
  "7736 is the number of labeled Eulerian digraphs with 5 vertices",
  "7744 is the smallest known square with no isolated digits",
  "7752 is the generalized Catalan number C(14,5)",
  "7754 is the number of binary cube-free words of length 21",
  "78 is a triangular number, and its factorization makes it a sphenic number",
  "7811 is the number of ordered sequences of coins totaling 32 cents",
  "7820 is the Stirling number of the second kind S(17,15)",
  "783 is the number of 11-ominoes that tile the plane by translation",
  "7849 is the number of connected 6-regular graphs with 12 vertices",
  "7874 is the smallest number n for which n concatenated with n+2 is a square",
  "7882 is a structured pentagonal hexacontahedral number",
  "7888 is a value of n where f(n) is the product of the digits of n",
  "79 is the n value of the Wagstaff prime 201487636602438195784363",
  "7913 is a value of n for which s(n-1) = s(n+1)",
  "7917 is the number of partitions of 57 into distinct parts",
  "7920 is the order of the smallest sporadic group",
  "7937 is the smallest number whose cube contains 5 consecutive 9's",
  "7953 is the number of domino tilings of a 3×14 rectangle",
  "7964 is a value of n for which f(n) = f(reverse(n))",
  "797 is the number of functional graphs on 9 vertices",
  "798 is the number of ternary square-free words of length 16",
  "7997 is a palindrome in base 4 and in base 10",
  "8 is the largest cube in the Fibonacci sequence",
  "80 is a ménage number, and is a Harshad number number in base 10",
  "8000 is the smallest cube which is also the sum of 4 consecutive cubes",
  "8012 is the number of 3-connected planar maps with 18 edges",
  "8026 is the number of planar partitions of 19",
  "803 is a value of n for which s(n) is a repdigit",
  "805 is the number of possible positions in Checkers after 4 moves",
  "8071 is the number of connected graphs with 11 edges",
  "8083 is a value of n for which n concatenated with n-2 is square",
  "81 is the square of 9 and the fourth power of 3",
  "8104 is equal to the sum of its anti-divisors",
  "8121 is the smallest number whose cube contains seven 5's",
  "8129 is a member of the Fibonacci-type sequence starting with 2 and 7",
  "814 is a value of n so that n(n+5) is a palindrome",
  "8226 is the sum of its proper divisors that contain the digit 4",
  "8230 is the number of necklaces with 8 beads, each one of 4 colors",
  "827 is the number of asymmetric trees with 11 vertices",
  "8280 is the smaller number in a Ruth-Aaron pair",
  "8281 is the only 4-digit square whose two 2-digit pairs are consecutive",
  "829 is a value of n for which p(n) is the product of the digits of n",
  "83 is the number of strongly connected digraphs with 4 vertices",
  "8317 is the number of trees on 33 vertices with diameter 4",
  "8338 is a value of n so that n(n+4) is a palindrome",
  "8342 is the number of partitions of 53 in which no part occurs only once",
  "8345 is the smallest number in base 6 to have 6 different digits",
  "836 is a non-palindrome with a palindromic square",
  "8369 is the largest prime factor of 2 × 3 × 5 × 7 × 11 × 13 × 17 - 1",
  "8385 is a structured great rhombicubeoctahedral number",
  "8390 is the number of linear spaces on 7 labeled points",
  "8393 is a value of n for which s(reverse(n)) = f(n)",
  "84 is the largest order of a permutation of 14 elements",
  "840 is the smallest number divisble by 1 through 8",
  "8400 is the number of legal queen moves in Chess",
  "8404 is the number of connected graphs with 9 vertices and 13 edges",
  "8406 is the number of ways to divide 8 black and 8 white beads into piles",
  "841 is a square that is also the sum of 2 consecutive squares",
  "8420 is the number of symmetric ways to fold a strip of 20 stamps",
  "8441 is the sum of the cubes of 3 consecutive primes",
  "8451 is the number of 3×3 matrices in base 3 with determinant 0",
  "8463 is the smaller number in a Ruth-Aaron pair",
  "8474 is the maximum number of regions a cube can be cut into with 37 cuts",
  "8475 is the first of four consecutive squareful numbers",
  "849 is a value of n for which s(n-1) = s(n+1)",
  "8494 is a value of n for which s(n) = f(n) + f(n-1) + f(n-2)",
  "8499 is the sum of the squares of 3 consecutive primes",
  "852 is the number of 6-colorable connected graphs with 7 vertices",
  "853 is the number of connected graphs with 7 vertices",
  "8548 is the sum of the squares of 4 consecutive primes",
  "856 is a member of the Fibonacci-type sequence starting with 1 and 9",
  "857 is a value of n for which f(n) = f(n-1) + f(n-2)",
  "858 is the smallest palindrome with 4 different prime factors",
  "8582 is the number of monoids of order 7 with 5 idempotents",
  "8591 is the number of partitions of 42 that do not contain 1 as a part",
  "8599 is the number of forests with 14 vertices",
  "86 is the 25th distinct semiprime and the 13th of the form (2q)",
  "8602 is the generalized Catalan number C(20,4)",
  "8626 is the number of asymmetric trees with 13 vertices",
  "863 is a value of n so that n(n+6) is a palindrome",
  "8633 is the product of two consecutive primes",
  "864 is the number of partitions of 38 into distinct parts",
  "8641 is the number of ways to tile a 3×25 rectangle with 3×1 rectangles",
  "8658 is the sum of the first 4 perfect numbers",
  "8697 is a structured octagonal anti-diamond number",
  "87 is the sum of the squares of the first four primes",
  "87 is the twenty-sixth distinct semiprime and the eighth of the form (3q)",
  "8721 is a value of n for which f(n) and s(n) are square",
  "8739 is a permutation of the sum of its proper divisors",
  "8748 is the largest number whose prime factors add to 25",
  "8778 is both a triangular number and 3 times a triangular number",
  "8779 is is the largest prime factor of 100000000001",
  "8785 is the number of 13-iamonds without holes",
  "88 is one of only 2 numbers known whose square has no isolated digits",
  "8801 is the magic constant of a 26×26 magic square",
  "8808 is the number of partitions of 58 into distinct parts",
  "8813 is the number of chiral invertible knots with 14 crossings",
  "8814 is the number of multigraphs with 27 vertices and 4 edges",
  "8819 is the smallest number whose square begins with four 7's",
  "8826 is the sum of its proper divisors that contain the digit 4",
  "8854 is the number of possible rows in a 20×20 crossword puzzle",
  "8857 is a structured truncated tetrahedral number",
  "8867 is the smallest prime with multiplicative persistence 6",
  "8887 is a value of n for which s(n) is a repdigit",
  "891 is the number of unlabeled distributive lattices with 15 elements",
  "8944 is the sum of the cubes of the first 7 primes",
  "8954 is the first of four consecutive squareful numbers",
  "8980 is a value of n for which the first n binary digits of p form a prime",
  "8999 is the smallest number whose digits add to 35",
  "8e+67 is the number of ways to order the cards in a 52-card deck",
  "9 is the sum of the digits of 41 is 5, and 41-5 = 36",
  "9002 is a value of n so that n(n+7) is a palindrome",
  "9005 is the number of inequivalent Ferrers graphs with 36 points",
  "9012 is the sum of its proper divisors that contain the digit 5",
  "902 is a value of n so that n(n+7) is a palindrome",
  "9045 is the number of ways to 18-color the faces of a tetrahedron",
  "907 is the largest n so that Q(vn) has class number 3",
  "9091 is the only prime known whose reciprocal has period 10",
  "9099 is the number of ways to 3-color the faces of a dodecahedron",
  "910 is the generalized Catalan number C(11,4)",
  "9105 is the number of possible positions in Checkers after 6 moves",
  "9119 is the number of symmetric plane partitions of 34",
  "9121 is the number of possibilities for the last 5 digits of a square",
  "9138 is the number of 13-iamonds without bilateral symmetry",
  "9154 is a value of n for which f(n) and s(n) are square",
  "9172 is the number of connected planar maps with 7 edges",
  "9174 is the sum of its proper divisors that contain the digit 5",
  "9183 is the number of sets of distinct positive integers with mean 8",
  "9198 is the number of ternary square-free words of length 25",
  "9217 is the total number of digits of all binary numbers of length 1-10",
  "9234 is the number of multigraphs with 7 vertices and 10 edges",
  "9248 is the number of possible rook moves on a 17×17 chessboard",
  "925 is the number of partitions of 37 in which no part occurs only once",
  "9252 is the number of necklaces with 10 white and 10 black beads",
  "9253 is the smallest number that appears in its factorial 9 times",
  "9268 is a value of n for which 2f(n) = f(n+1)",
  "9282 is the product of three consecutive Fibonacci numbers",
  "9285 is the number of 16-hexes with reflectional symmetry",
  "9289 is a Tetranacci-like number starting from 1, 1, 1, and 1",
  "93 is the twenty-eighth distinct semiprime and the ninth of the form (3q)",
  "930 is the number of even permutations on 7 elements with no fixed points",
  "9330 is the Stirling number of the second kind S(10,3)",
  "9339 is a value of n for which f(n) = f(n-2) - f(n-1)",
  "9360 is a value of n for which s(n-1) = s(n+1)",
  "9363 is the number of tilted rectangles with vertices in a 15×15 grid",
  "9364 is the number of connected digraphs with 5 vertices",
  "9385 is the sum of consecutive squares in 2 ways",
  "9394 is a value of n so that n(n+8) is a palindrome",
  "9396 is the number of symmetric 3×3 matrices in base 6 with determinant 0",
  "9408 is the number of reduced 6×6 Latin squares",
  "9415 is the sum of the first 19 numbers that have digit sum 19",
  "942 is the smallest number whose cube contains five 8's",
  "9428 is the smallest number whose square begins with four 8's",
  "9431 is a number n for which n, n+2, n+6, and n+8 are all prime",
  "9432 is the number of 3-colored rooted trees with 6 vertices",
  "9439 is prime, and 5 closest primes are all smaller",
  "9451 is the number of binary rooted trees with 19 vertices",
  "9468 is the sum of its proper divisors that contain the digit 7",
  "948 is the number of symmetric plane partitions of 24",
  "9496 is the number of 10×10 symmetric permutation matrices",
  "9497 is the number of bicentered trees with 16 vertices",
  "95 is the thirtieth distinct semiprime and the fifth of the form (5q)",
  "950 is the generalized Catalan number C(17,3)",
  "951 is the number of functions from 8 unlabeled points to themselves",
  "953000000000000 is the largest known Motzkin prime",
  "9564 is the number of paraffins with 10 carbon atoms",
  "958 is the number of labeled 3-colorable graphs with 5 vertices",
  "9592 is the number of primes with 5 or fewer digits",
  "960 is the sum of its digits and the cube of its digits",
  "9608 is the number of digraphs with 5 vertices",
  "961 is a square whose digits can be rotated to give another square",
  "9615 is the smallest number whose cube starts with 5 identical digits",
  "963 is a value of n for which p(n) is the product of the digits of n",
  "966 is the Stirling number of the second kind S(8,3)",
  "967 is the number of 6-digit triangular numbers",
  "9670 is the number of 8-digit triangular numbers",
  "9677 is a prime that remains prime if any digit is deleted",
  "970 is the number of connected graphs with 8 vertices and 17 edges",
  "973 is the number of inequivalent asymmetric Ferrers graphs with 25 points",
  "9738 is the number of trees on 22 vertices with diameter 5",
  "975 is the number of 11-ominoes that contain 1 hole",
  "9770 is the number of Hamiltonian cycles of a 4×12 rectangle graph",
  "9777 is the number of graphs on 8 vertices with no isolated vertices",
  "9784 is the number of 2 state Turing machines which halt",
  "9789 is the smallest number that appears in its factorial 11 times",
  "9792 is the number of partitions of 59 into distinct parts",
  "9797 is the product of two consecutive primes",
  "980 is the number of trees on 23 vertices with diameter 4",
  "9800 is the largest 4-digit number with single digit prime factors",
  "982 is the number of partitions of 39 into distinct parts",
  "9823 is the number of centered trees with 16 vertices",
  "9843 is the number of vertices in a Sierpinski triangle of order 8",
  "9868 is the number of hydrocarbons with 10 carbon atoms",
  "9871 is the largest 4-digit prime with different digits",
  "9876 is the largest 4-digit number with different digits",
  "989 is the smallest number so that it and its reverse are divisible by 43",
  "9894 is the number of 3-colored trees with 7 vertices",
  "99 is the ninth repdigit, a palindromic number and a Kaprekar number",
  "990 is a triangular number that is the product of 3 consecutive integers",
  "9901 is the only prime known whose reciprocal has period 12",
  "9912 is the number of graceful permutations of length 14",
  "9928 is a value of n for which reverse(f(n)) = f(reverse(n))",
  "993 is the number of paraffins with 8 carbon atoms",
  "9959 is a member of the Fibonacci-type sequence starting with 2 and 5",
  "9966 is the largest 4-digit strobogrammatic number",
  "9985 is the number of hyperbolic knots with 13 crossings",
  "9988 is the number of prime knots with 13 crossings",
  "Infinity is the largest proven Leyland prime as of 2010",
  "10 is a Harshad number in bases 2, 3, 5, 6, 9 and all others above"
];
